//! Test fixtures - reusable model definitions for testing
//!
//! This module contains commonly used test models that can be shared across tests.
//! LifecycleHooks are auto-generated by #[ormada_model] - no manual impl needed!

use ormada::prelude::*;

/// Simple test item model - used for basic CRUD tests
pub mod simple_item {
    use super::*;

    #[ormada_model(table = "simple_items")]
    pub struct SimpleItem {
        #[primary_key]
        pub id: i32,
        pub value: i32,
    }
}

/// Rich item model - for testing with multiple field types
pub mod rich_item {
    use super::*;

    #[ormada_model(table = "rich_items")]
    pub struct RichItem {
        #[primary_key]
        pub id: i32,
        pub value: i32,
        #[max_length(100)]
        pub name: String,
        pub created_at: DateTimeWithTimeZone,
    }
}

/// Aggregate test item - for testing aggregations with NULLs
pub mod agg_item {
    use super::*;

    #[ormada_model(table = "agg_items")]
    pub struct AggItem {
        #[primary_key]
        pub id: i32,
        pub int_value: Option<i32>,
        pub dec_value: Option<i64>,
        pub category: i32,
    }
}

// Fixture tests are in tests/EXAMPLE_TEST.rs
